server:
  port: 6001

spring:
  application:
    name: store-login-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/store
      username: root
      password: renyihan21
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

feign:
  hystrix:
    enabled: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    开启mp的输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      配置统一的前缀
      table-prefix: t_

file:
  path: D:\Baidu_Download\信息\图片\

